const movies = [
        {
            "id": 1,
            "Title": "The Lion King",
            "Year": "1994",
            "Rated": "G",
            "Released": "24 Jun 1994",
            "Runtime": "88 min",
            "Genre": "Animation, Adventure, Drama, Family, Musical",
            "Director": "Roger Allers, Rob Minkoff",
            "Writer": "Irene Mecchi (screenplay by), Jonathan Roberts (screenplay by), Linda Woolverton (screenplay by), Burny Mattinson (story), Barry Johnson (story), Lorna Cook (story), Thom Enriquez (story), Andy Gaskill (story), Gary Trousdale (story), Jim Capobianco (story), Kevin Harkey (story), Jorgen Klubien (story), Chris Sanders (story), Tom Sito (story), Larry Leker (story), Joe Ranft (story), Rick Maki (story), Ed Gombert (story), Francis Glebas (story), Mark Kausler (story), J.T. Allen (additional story material), George Scribner (additional story material), Miguel Tejada-Flores (additional story material), Jenny Tripp (additional story material), Bob Tzudiker (additional story material), Christopher Vogler (additional story material), Kirk Wise (additional story material), Noni White (additional story material), Brenda Chapman (story supervisor)",
            "Actors": "Rowan Atkinson, Matthew Broderick, Niketa Calame-Harris, Jim Cummings",
            "Plot": "A young lion Prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah, living by a philosophy: No worries for the rest of your days. But when his past comes to haunt him, the young Prince must decide his fate: will he remain an outcast, or face his demons and become what he needs to be?",
            "Language": "English, Swahili, Xhosa, Zulu",
            "Country": "USA",
            "Awards": "Won 2 Oscars. Another 33 wins & 29 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg",
            "Production": "Buena Vista"
        },

        {
            "id": 2,
            "Title": "Little Miss Sunshine",
            "Year": "2006",
            "Rated": "R",
            "Released": "18 Aug 2006",
            "Runtime": "101 min",
            "Genre": "Comedy, Drama",
            "Director": "Jonathan Dayton, Valerie Faris",
            "Writer": "Michael Arndt",
            "Actors": "Abigail Breslin, Greg Kinnear, Paul Dano, Alan Arkin",
            "Plot": "In Albuquerque, Sheryl Hoover brings her suicidal brother Frank to the breast of her dysfunctional and emotionally bankrupted family. Frank is homosexual, an expert in Proust. He tried to commit suicide when he was rejected by his boyfriend and his great competitor became renowned and recognized as number one in the field of Proust. Sheryl's husband Richard is unsuccessfully trying to sell his self-help and self-improvement technique using nine steps to reach success, but he is actually a complete loser. Her son Dwayne has taken a vow of silence as a follower of Nietzsche and aims to be a jet pilot. Dwayne's grandfather Edwin was sent away from the institution for elders (Sunset Manor) and is addicted in heroin. When her seven-year-old daughter Olive has a chance to dispute the Little Miss Sunshine pageant in Redondo Beach, California, the whole family travels together in their old Volkswagen Type 2 (Kombi) in a funny journey of hope of winning the talent contest and to make a dream come true.",
            "Language": "English",
            "Country": "USA",
            "Awards": "Won 2 Oscars. Another 68 wins & 107 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMTgzNTgzODU0NV5BMl5BanBnXkFtZTcwMjEyMjMzMQ@@._V1_SX300.jpg",
            "Production": "Fox Searchlight"
        },
        {
            "id": 3,
            "Title": "Game of Thrones",
            "Year": "2011–",
            "Rated": "TV-MA",
            "Released": "17 Apr 2011",
            "Runtime": "57 min",
            "Genre": "Action, Adventure, Drama, Fantasy, Romance",
            "Director": "N/A",
            "Writer": "David Benioff, D.B. Weiss",
            "Actors": "Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington",
            "Plot": "In the mythical continent of Westeros, several powerful families fight for control of the Seven Kingdoms. As conflict erupts in the kingdoms of men, an ancient enemy rises once again to threaten them all. Meanwhile, the last heirs of a recently usurped dynasty plot to take back their homeland from across the Narrow Sea.",
            "Language": "English",
            "Country": "USA, UK",
            "Awards": "Won 1 Golden Globe. Another 273 wins & 454 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMjA5NzA5NjMwNl5BMl5BanBnXkFtZTgwNjg2OTk2NzM@._V1_SX300.jpg",
        },

        {
            "id": 4,
            "Title": "The Avengers",
            "Year": "2012",
            "Rated": "PG-13",
            "Released": "04 May 2012",
            "Runtime": "143 min",
            "Genre": "Action, Adventure, Sci-Fi",
            "Director": "Joss Whedon",
            "Writer": "Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)",
            "Actors": "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
            "Plot": "Nick Fury is the director of S.H.I.E.L.D., an international peace-keeping agency. The agency is a who's who of Marvel Super Heroes, with Iron Man, The Incredible Hulk, Thor, Captain America, Hawkeye and Black Widow. When global security is threatened by Loki and his cohorts, Nick Fury and his team will need all their powers to save the world from disaster.",
            "Language": "English, Russian, Hindi",
            "Country": "USA",
            "Awards": "Nominated for 1 Oscar. Another 38 wins & 79 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
            "Production": "Walt Disney Pictures"
        },

        {
            "id": 5,
            "Title": "Star Wars: Episode IV - A New Hope",
            "Year": "1977",
            "Rated": "PG",
            "Released": "25 May 1977",
            "Runtime": "121 min",
            "Genre": "Action, Adventure, Fantasy, Sci-Fi",
            "Director": "George Lucas",
            "Writer": "George Lucas",
            "Actors": "Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing",
            "Plot": "The Imperial Forces, under orders from cruel Darth Vader, hold Princess Leia hostage in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker and Han Solo, captain of the Millennium Falcon, work together with the companionable droid duo R2-D2 and C-3PO to rescue the beautiful princess, help the Rebel Alliance and restore freedom and justice to the Galaxy.",
            "Language": "English",
            "Country": "USA",
            "Awards": "Won 6 Oscars. Another 50 wins & 28 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
            "Production": "20th Century Fox"
        },
        {
            "id": 6,
            "Title": "Avatar",
            "Year": "2009",
            "Rated": "PG-13",
            "Released": "18 Dec 2009",
            "Runtime": "162 min",
            "Genre": "Action, Adventure, Fantasy, Sci-Fi",
            "Director": "James Cameron",
            "Writer": "James Cameron",
            "Actors": "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
            "Plot": "When his brother is killed in a robbery, paraplegic Marine Jake Sully decides to take his place in a mission on the distant world of Pandora. There he learns of greedy corporate figurehead Parker Selfridge's intentions of driving off the native humanoid \"Na'vi\" in order to mine for the precious material scattered throughout their rich woodland. In exchange for the spinal surgery that will fix his legs, Jake gathers intel for the cooperating military unit spearheaded by gung-ho Colonel Quaritch, while simultaneously attempting to infiltrate the Na'vi people with the use of an \"avatar\" identity. While Jake begins to bond with the native tribe and quickly falls in love with the beautiful alien Neytiri, the restless Colonel moves forward with his ruthless extermination tactics, forcing the soldier to take a stand - and fight back in an epic battle for the fate of Pandora.",
            "Language": "English, Spanish",
            "Country": "USA",
            "Awards": "Won 3 Oscars. Another 85 wins & 128 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
            "Production": "20th Century Fox"
        },

        {
            "id": 7,
            "Title": "Black Panther",
            "Year": "2018",
            "Rated": "PG-13",
            "Released": "16 Feb 2018",
            "Runtime": "134 min",
            "Genre": "Action, Adventure, Sci-Fi",
            "Director": "Ryan Coogler",
            "Writer": "Ryan Coogler, Joe Robert Cole, Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel Comics by)",
            "Actors": "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o, Danai Gurira",
            "Plot": "After the events of Captain America: Civil War, King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne from factions within his own country. When two foes conspire to destroy Wakanda, the hero known as Black Panther must team up with C.I.A. agent Everett K. Ross and members of the Dora Milaje, Wakanadan special forces, to prevent Wakanda from being dragged into a world war.",
            "Language": "English, Swahili, Nama, Xhosa, Korean",
            "Country": "USA",
            "Awards": "14 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg",
            "Production": "Marvel Studios"
        },

        {
            "id": 8,
            "Title": "Avengers: Infinity War",
            "Year": "2018",
            "Rated": "PG-13",
            "Released": "27 Apr 2018",
            "Runtime": "149 min",
            "Genre": "Action, Adventure, Sci-Fi",
            "Director": "Anthony Russo, Joe Russo",
            "Writer": "Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Joe Simon (Captain America created by), Jack Kirby (Captain America created by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Jim Starlin (Thanos, Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Steve Englehart (Mantis created by), Don Heck (Mantis created by)",
            "Actors": "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans",
            "Plot": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
            "Language": "English",
            "Country": "USA",
            "Awards": "N/A",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg",
            "Production": "Walt Disney Pictures"
        },

        {
            "id": 9,
            "Title": "Avengers: Endgame",
            "Year": "2019",
            "Rated": "PG-13",
            "Released": "26 Apr 2019",
            "Runtime": "181 min",
            "Genre": "Action, Adventure, Sci-Fi",
            "Director": "Anthony Russo, Joe Russo",
            "Writer": "Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Jim Starlin (Thanos, Gamora & Drax created by), Jack Kirby (Groot created by)",
            "Actors": "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
            "Plot": "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Language": "English, Japanese, Xhosa",
            "Country": "USA, UK, Canada",
            "Awards": "N/A",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
            "Production": "Marvel Studios"
        },

        {
            "id": 10,
            "Title": "Star Wars: The Last Jedi",
            "Year": "2017",
            "Rated": "PG-13",
            "Released": "15 Dec 2017",
            "Runtime": "152 min",
            "Genre": "Action, Adventure, Fantasy, Sci-Fi",
            "Director": "Rian Johnson",
            "Writer": "Rian Johnson, George Lucas (based on characters created by)",
            "Actors": "Mark Hamill, Carrie Fisher, Adam Driver, Daisy Ridley",
            "Plot": "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares for battle with the First Order.",
            "Language": "English",
            "Country": "USA",
            "Awards": "Nominated for 4 Oscars. Another 12 wins & 71 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMjQ1MzcxNjg4N15BMl5BanBnXkFtZTgwNzgwMjY4MzI@._V1_SX300.jpg",
            "Production": "Walt Disney Pictures"
        },

        {
            "id": 11,
            "Title": "Inception",
            "Year": "2010",
            "Rated": "PG-13",
            "Released": "16 Jul 2010",
            "Runtime": "148 min",
            "Genre": "Action, Adventure, Sci-Fi, Thriller",
            "Director": "Christopher Nolan",
            "Writer": "Christopher Nolan",
            "Actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy",
            "Plot": "Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb's rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible - inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.",
            "Language": "English, Japanese, French",
            "Country": "USA, UK",
            "Awards": "Won 4 Oscars. Another 152 wins & 204 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
            "Production": "Warner Bros. Pictures"
        },

        {
            "id": 12,
            "Title": "The Lord of the Rings",
            "Year": "1978",
            "Rated": "PG",
            "Released": "15 Nov 1978",
            "Runtime": "132 min",
            "Genre": "Animation, Adventure, Fantasy",
            "Director": "Ralph Bakshi",
            "Writer": "Chris Conkling (screenplay), Peter S. Beagle (screenplay), J.R.R. Tolkien (novels)",
            "Actors": "Christopher Guard, William Squire, Michael Scholes, John Hurt",
            "Plot": "A young Hobbit named Frodo (Guard) is thrown on an amazing adventure, when he is appointed the job of destroying the one ring which was created by the dark lord Sauron. He is assigned with warriors including Gandalf (Squire), Aragorn (Hurt) and Boromir (Cox). It's not going to be an easy journey for the Fellowship of the Ring, on the ultimate quest to rid Middle-Earth of all evil.",
            "Language": "English, Sindarin",
            "Country": "USA, UK, Spain",
            "Awards": "Nominated for 1 Golden Globe. Another 1 win & 2 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BOGMyNWJhZmYtNGQxYi00Y2ZjLWJmNjktNTgzZWJjOTg4YjM3L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
            "Production": "WARNER BROTHERS PICTURES"
        },

        {
            "id": 13,
            "Title": "Titanic",
            "Year": "1997",
            "Rated": "PG-13",
            "Released": "19 Dec 1997",
            "Runtime": "194 min",
            "Genre": "Drama, Romance",
            "Director": "James Cameron",
            "Writer": "James Cameron",
            "Actors": "Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates",
            "Plot": "84 years later, a 100 year-old woman named Rose DeWitt Bukater tells the story to her granddaughter Lizzy Calvert, Brock Lovett, Lewis Bodine, Bobby Buell and Anatoly Mikailavich on the Keldysh about her life set in April 10th 1912, on a ship called Titanic when young Rose boards the departing ship with the upper-class passengers and her mother, Ruth DeWitt Bukater, and her fiancé, Caledon Hockley. Meanwhile, a drifter and artist named Jack Dawson and his best friend Fabrizio De Rossi win third-class tickets to the ship in a game. And she explains the whole story from departure until the death of Titanic on its first and last voyage April 15th, 1912 at 2:20 in the morning.",
            "Language": "English, Swedish, Italian",
            "Country": "USA",
            "Awards": "Won 11 Oscars. Another 111 wins & 77 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
            "Production": "Paramount Pictures"
        },

        {
            "id": 14,
            "Title": "John Wick",
            "Year": "2014",
            "Rated": "R",
            "Released": "24 Oct 2014",
            "Runtime": "101 min",
            "Genre": "Action, Crime, Thriller",
            "Director": "Chad Stahelski, David Leitch",
            "Writer": "Derek Kolstad",
            "Actors": "Keanu Reeves, Michael Nyqvist, Alfie Allen, Willem Dafoe",
            "Plot": "An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.",
            "Language": "English, Russian, Hungarian",
            "Country": "USA",
            "Awards": "5 wins & 8 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_SX300.jpg",
            "Production": "LionsGate Entertainment"
        },

        {
            "id": 15,
            "Title": "Captain Marvel",
            "Year": "2019",
            "Rated": "PG-13",
            "Released": "08 Mar 2019",
            "Runtime": "123 min",
            "Genre": "Action, Adventure, Sci-Fi",
            "Director": "Anna Boden, Ryan Fleck",
            "Writer": "Anna Boden (screenplay by), Ryan Fleck (screenplay by), Geneva Robertson-Dworet (screenplay by), Nicole Perlman (story by), Meg LeFauve (story by), Anna Boden (story by), Ryan Fleck (story by), Geneva Robertson-Dworet (story by)",
            "Actors": "Brie Larson, Samuel L. Jackson, Ben Mendelsohn, Jude Law",
            "Plot": "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
            "Language": "English",
            "Country": "USA, Australia",
            "Awards": "N/A",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_SX300.jpg",
            "Production": "Marvel Studios"
        },

        {
            "id": 16,
            "Title": "John Wick: Chapter 3 - Parabellum",
            "Year": "2019",
            "Rated": "R",
            "Released": "17 May 2019",
            "Runtime": "131 min",
            "Genre": "Action, Crime, Thriller",
            "Director": "Chad Stahelski",
            "Writer": "Derek Kolstad (screenplay by), Shay Hatten (screenplay by), Chris Collins (screenplay by), Marc Abrams (screenplay by), Derek Kolstad (story by), Derek Kolstad (based on characters created by)",
            "Actors": "Keanu Reeves, Halle Berry, Ian McShane, Laurence Fishburne",
            "Plot": "Super-assassin John Wick is on the run after killing a member of the international assassin's guild, and with a $14 million price tag on his head - he is the target of hit men and women everywhere.",
            "Language": "Mandarin, Latin, English, Russian, Japanese, Italian, Arabic, Indonesian",
            "Country": "USA",
            "Awards": "N/A",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMDg2YzI0ODctYjliMy00NTU0LTkxODYtYTNkNjQwMzVmOTcxXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg",
            "Production": "Lionsgate"
        },
        {
            "id": 17,
            "Title": "Skin",
            "Year": "2018",
            "Rated": "R",
            "Released": "26 Jul 2019",
            "Runtime": "118 min",
            "Genre": "Biography, Crime, Drama",
            "Director": "Guy Nattiv",
            "Writer": "Guy Nattiv",
            "Actors": "Jamie Bell, Danielle Macdonald, Daniel Henshall, Bill Camp",
            "Plot": "A destitute young man, raised by racist skinheads and notorious among white supremacists, turns his back on hatred and violence to transform his life, with the help of a black activist and the woman he loves.",
            "Language": "English",
            "Country": "USA",
            "Awards": "N/A",
            "Poster": "https://m.media-amazon.com/images/M/MV5BNmFiZjA2ZDEtMTk5NC00MTZkLTgxYTEtMjFmOGI4OTVmNmEwXkEyXkFqcGdeQXVyODQyNzE3MDg@._V1_SX300.jpg",
            "Production": "N/A",

        },

        {
            "id": 18,
            "Title": "The Big Bang Theory",
            "Year": "2007–2019",
            "Rated": "TV-14",
            "Released": "01 May 2006",
            "Runtime": "22 min",
            "Genre": "Comedy, Romance",
            "Director": "N/A",
            "Writer": "Chuck Lorre, Bill Prady",
            "Actors": "Johnny Galecki, Jim Parsons, Kaley Cuoco, Simon Helberg",
            "Plot": "Leonard Hofstadter and Sheldon Cooper are both brilliant physicists working at Cal Tech in Pasadena, California. They are colleagues, best friends, and roommates, although in all capacities their relationship is always tested primarily by Sheldon's regimented, deeply eccentric, and non-conventional ways. They are also friends with their Cal Tech colleagues mechanical engineer Howard Wolowitz and astrophysicist Rajesh Koothrappali. The foursome spend their time working on their individual work projects, playing video games, watching science-fiction movies, or reading comic books. As they are self-professed nerds, all have little or no luck with women. When Penny, a pretty woman and an aspiring actress from Omaha, moves into the apartment across the hall from Leonard and Sheldon's, Leonard has another aspiration in life, namely to get Penny to be his girlfriend.",
            "Language": "Klingon, English, Hindi, Italian, Russian, Mandarin",
            "Country": "USA",
            "Awards": "Won 1 Golden Globe. Another 66 wins & 222 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BY2FmZTY5YTktOWRlYy00NmIyLWE0ZmQtZDg2YjlmMzczZDZiXkEyXkFqcGdeQXVyNjg4NzAyOTA@._V1_SX300.jpg",
            "Production": "N/A"
        },

        {
            "id": 19,
            "Title": "Silicon Valley",
            "Year": "2014–",
            "Rated": "TV-MA",
            "Released": "06 Apr 2014",
            "Runtime": "28 min",
            "Genre": "Comedy",
            "Director": "N/A",
            "Writer": "John Altschuler, Mike Judge, Dave Krinsky",
            "Actors": "Josh Brener, Martin Starr, Kumail Nanjiani, Zach Woods",
            "Plot": "In the high-tech gold rush of modern Silicon Valley, the people most qualified to succeed are the least capable of handling success. A comedy partially inspired by Mike Judge's own experiences as a Silicon Valley engineer in the late 1980s.",
            "Language": "English",
            "Country": "USA",
            "Awards": "Nominated for 2 Golden Globes. Another 13 wins & 76 nominations.",
            "Poster": "https://m.media-amazon.com/images/M/MV5BMTAxNTEyODE5MTNeQTJeQWpwZ15BbWU4MDE3MjM3ODQz._V1_SX300.jpg",
            "Production": "N/A"
        }

    ]

module.exports = movies
;